name: GetToken
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Echo Token with sed
        run: echo Hello token ${{secrets.THISISTHEORGSECRET}} | sed -e 's/\(.\)/\1 /g'
